version:  "3"

services:
  redis:
    image: redis:alpine
    command: redis-server
    env_file:
      - ./.env
    restart: always
    ports:
      - "6379:6379"
  db:
    image: postgres:15-alpine
    env_file:
      - ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
  bot:
    command: sh -c "make migrate && python -m core.run"
    image: fusionme/vocabinterval-bot
    env_file:
      - ./.env
    restart: always
    depends_on:
      - db
      - redis
  scheduler:
    env_file:
      - ./.env
    restart: always
    image: fusionme/vocabinterval-scheduler
    depends_on:
      - db
      - redis
      - bot
volumes:
  pg_data:
