"""First

Revision ID: 31afe3a45704
Revises: 
Create Date: 2024-01-29 18:20:03.814816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31afe3a45704'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=32), nullable=True),
    sa.Column('reg_date', sa.DATE(), nullable=True),
    sa.Column('upd_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('cards',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('foreign_word', sa.VARCHAR(length=255), nullable=True),
    sa.Column('translation', sa.VARCHAR(length=255), nullable=False),
    sa.Column('transcription', sa.VARCHAR(length=255), nullable=True),
    sa.Column('example_usage', sa.VARCHAR(length=512), nullable=True),
    sa.Column('created_at', sa.DATE(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_foreign_word'), 'cards', ['foreign_word'], unique=False)
    op.create_index(op.f('ix_cards_id'), 'cards', ['id'], unique=False)
    op.create_table('repetitions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('card_id', sa.BigInteger(), nullable=True),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('next_review_date', sa.DATE(), nullable=True),
    sa.CheckConstraint('level >= 0 AND level <= 7', name='check_level_range'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_index(op.f('ix_repetitions_id'), 'repetitions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repetitions_id'), table_name='repetitions')
    op.drop_table('repetitions')
    op.drop_index(op.f('ix_cards_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_foreign_word'), table_name='cards')
    op.drop_table('cards')
    op.drop_table('users')
    # ### end Alembic commands ###
