"""add_page_size_dictionary_column

Revision ID: c79d0c06a016
Revises: 31afe3a45704
Create Date: 2024-02-29 15:29:44.842417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c79d0c06a016'
down_revision: Union[str, None] = '31afe3a45704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('page_size_dictionary', sa.Integer(), nullable=True, server_default='10'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'page_size_dictionary')
    # ### end Alembic commands ###
